#
# Use this dockerfile to run api-tools.
#
# Start the server using docker-compose:
#
#   docker-compose build
#   docker-compose up
#
# You can install dependencies via the container:
#
#   docker-compose run api-tools composer install
#
# You can manipulate dev mode from the container:
#
#   docker-compose run api-tools composer development-enable
#   docker-compose run api-tools composer development-disable
#   docker-compose run api-tools composer development-status
#
# OR use plain old docker 
#
#   docker build -f Dockerfile-dev -t api-tools .
#   docker run -it -p "8080:80" -v $PWD:/var/www api-tools
#
FROM php:7.4-apache

# Laminas
RUN apt-get update \
 && apt-get install -y git zlib1g-dev libicu-dev \
   libzip-dev \
   zip \
 && docker-php-ext-configure zip \
 && docker-php-ext-install zip \
  && docker-php-ext-configure intl \
  && docker-php-ext-install intl \
 && a2enmod rewrite \
 && sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/sites-available/000-default.conf \
 && mv /var/www/html /var/www/public \
 && curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer \
 && echo "AllowEncodedSlashes On" >> /etc/apache2/apache2.conf

#Swoole
RUN apt-get update && apt-get install vim -y && \
    apt-get install openssl -y && \
    apt-get install libcurl4-gnutls-dev -y && \
    apt-get install libssl-dev -y && \
    apt-get install wget -y && \
    apt-get install git -y && \
    apt-get install procps -y && \
    apt-get install htop -y && \
    apt-get install net-tools -y
RUN cd /tmp && git clone https://github.com/openswoole/swoole-src.git && \
    cd swoole-src && \
    git checkout v4.8.1 && \
    phpize  && \
    ./configure --enable-openssl --enable-swoole-curl --enable-http2 --enable-mysqlnd && \
    make && make install
RUN touch /usr/local/etc/php/conf.d/openswoole.ini && \
        echo 'extension=openswoole.so' > /usr/local/etc/php/conf.d/zzz_openswoole.ini



WORKDIR /var/www

#
#COPY ./var /var
EXPOSE 8101
CMD ["/usr/local/bin/php", "/var/www/public/server.php"]
#